name: CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-minor-version: ["8", "9"]

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}
      CIBW_TEST_EXTRAS: test
      CIBW_TEST_COMMAND: pytest tests
      CIBW_BUILD: cp3${{ matrix.python-minor-version }}-manylinux_x86_64
      CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.${{ matrix.python-version }}

      - name: Set up Python tools
        run: pip install cibuildwheel poetry

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      #- name: Deploy wheels
      #  run: poetry publish --username $PYPI_USER --password $PYPI_PW
