name: CI & CD

on:
  push:
    tags: ["*"]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build wheels
        run: uv tool run cibuildwheel --output-dir dist

      - name: Publish wheels
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
