name: CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      min-numpy-version: "1.16.0"
      min-numpy-hash: "04/b6/d7faa70a3e3eac39f943cc6a6a64ce378259677de516bd899dd9eb8f9b32"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"

      - name: Install Python tools
        run: pip install poetry cibuildwheel

      - name: Build wheels for CPython 3.9
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest tests

      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp37-* cp38-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest tests
