name: CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        include:
          - sudo: required
            services:
              - docker
            env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
              PLAT=manylinux2014_x86_64

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python tools
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: pytest

      - name: Build wheels
        run: docker pull $DOCKER_IMAGE && docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD poetry build --format wheel

      #- name: Deploy wheels
      #  run: poetry publish --username $PYPI_USER --password $PYPI_PW
