name: CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python: [38, 39]
        include:
          - os: windows-latest
            bitness: 64
            platform_id: win_amd64
          - os: ubuntu-latest
            bitness: 64
            platform_id: manylinux_x86_64
          - os: macos-latest
            bitness: 64
            platform_id: macosx_x86_64

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}
      CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform_id }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python tools
        run: |
          pip install poetry cibuildwheel
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: pytest

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist

      #- name: Deploy wheels
      #  run: poetry publish --username $PYPI_USER --password $PYPI_PW
