name: CI & CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python tools
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: pytest

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0

      #- name: Deploy wheels
      #  run: poetry publish --username $PYPI_USER --password $PYPI_PW
