name: CI & CD

on:
  push:
    branches:
      - dev

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.9"

      - name: Install Python tools
        run: pip install poetry cibuildwheel

      - name: Build wheels for CPython 3.9
        run: cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {project}/tests

      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest tests

      - name: Show output
        run: ls dist
        env:
          CIBW_BUILD: "cp38-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest tests
