name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.8.7
          - 3.9.1

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: "${{ matrix.python }}"
        command: pip install --upgrade pip

      - name: Set up Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: pytest

      - name: Build wheels
        run: poetry build

      if: github.ref == 'refs/heads/master'
      - name: Deploy wheels
        run: poetry publish --username $PYPI_USER --password $PYPI_PW
