name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYPI_USER: ${{ secrets.PYPI_USER }}
      PYPI_PW: ${{ secrets.PYPI_PW }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'


      - name: Set up Python tools
        run: |
          pip install --upgrade pip poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: pytest

      - name: Build wheels
        run: poetry build

      - name: Deploy wheels
        run: poetry publish --username $PYPI_USER --password $PYPI_PW
