name: CI & CD

on:
  push:
    tags: ["*"]

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.10"

      - name: Install Python tools
        run: pip install poetry cibuildwheel --pre

      - name: Build wheels
        run: cibuildwheel --output-dir dist

      - name: Deploy wheels
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PW }}
